Task/ui design
Whiskarek/whiskarek.github.io pull request #2
Opened 2020-09-06 19:52 UTC by Whiskarek

2020-09-09 15:04 UTC, gmltA requested changes

2020-09-09 15:04 UTC, gmltA commented on constructor.html
> +<html>
Page language?

2020-09-09 15:04 UTC, gmltA commented on static/styles/coctail_card.css
> +    -webkit-box-orient: vertical;
Explain this, please.

2020-09-09 15:04 UTC, gmltA commented on static/styles/login.css
> +}
![image](https://user-images.githubusercontent.com/138737/92616341-c7567580-f2c6-11ea-96a5-073759b8fe76.png)

2020-09-09 18:15 UTC, Whiskarek commented on constructor.html
> +<html>
Добавил

2020-09-09 18:15 UTC, Whiskarek commented on static/styles/login.css
> +}
Убрал

2020-09-09 18:18 UTC, Whiskarek commented on static/styles/coctail_card.css
> +    -webkit-box-orient: vertical;
Пытался так ограничить количество видимых строк для блока.
Но это вообще из другой области)
Забыл удалить

2020-09-10 18:03 UTC, gmltA approved these changes

2020-09-10 21:00 UTC, merged